version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

    celery:
        build: .
        command: celery -A tasks worker --concurrency=6 --loglevel=info
        depends_on:
            - redis
        networks:
            - app-network
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0

    web:
        build: .
        command: python app.py
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
