version: "3.8"

services:
    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-network
        cpus: "0.3" # 최대 0.5 CPU 사용
        mem_limit: 1G # 최대 1Gi 메모리 사용

    celery:
        build: .
        command: celery -A tasks worker --concurrency=4 --loglevel=info
        depends_on:
            - redis
        networks:
            - app-network
        environment:
            - CELERY_BROKER_URL=redis://redis:6379/0
            - CELERY_RESULT_BACKEND=redis://redis:6379/0
        cpus: "1.5" # 최대 1.5 CPU 사용
        mem_limit: 5G # 최대 4GB 메모리 사용

    web:
        build: .
        command: python app.py
        ports:
            - "5000:5000"
        depends_on:
            - redis
        networks:
            - app-network
        cpus: "0.2" # 최대 1.0 CPU 사용
        mem_limit: 2G # 최대 2GB 메모리 사용

networks:
    app-network:
        driver: bridge
